uasapp/urls.py
from django.urls import path
from .views import *

app_name = "uasapp"

urlpatterns = [
    path("", HomeView.as_view()),
    path("contact/", ContactView.as_view()),
    path('register/', RegistrationView.as_view()),
    path('login/', LoginView.as_view()),
    path('logout/', LogoutView.as_view()),
    path('protected/', ProtectedView.as_view()),
    path('restricted/', RestrictedView.as_view()),
    path('article/list/', ArticleListView.as_view()),
    path('article/<int:pk>/detail/',
         ArticleDetailView.as_view(), name="articledetail"),
    path('article/create/', ArticleCreateView.as_view()),
    path("search", SearchView.as_view(), name='search'),








]

uasproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('uasapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uasapp/models.py
from django.db import models
from django.contrib.auth.models import User



class Article(models.Model):
	title=models.CharField(max_length=200)
	image=models.ImageField(upload_to='article')
	content=models.TextField()
	date=models.DateField(auto_now_add=True)
	author=models.ForeignKey(User,on_delete=models.CASCADE)
	view_count=models.PositiveIntegerField(default=0)

	def  __str__(self):
		return self.title


class Comment(models.Model):
	commentor=models.ForeignKey(User,on_delete=models.CASCADE)
	comment=models.TextField()
	date=models.DateTimeField(auto_now_add=True)
	article=models.ForeignKey(Article,on_delete=models.CASCADE)

	def __str__(self):
		return self.commentor.username

uasapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class RegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    email = forms.CharField(widget=forms.EmailInput())
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    def clean_confirm_password(self):
        a = self.cleaned_data['password']
        b = self.cleaned_data['confirm_password']
        if a != b:
            raise forms.ValidationError('your password did not match')
        return b

    def clean_username(self):
        a = self.cleaned_data['username']
        if User.objects.filter(username=a).exists():
            raise forms.ValidationError('please choose different username')
        return a


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'image', 'content', ]

uasapp/views.py
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import *
from .forms import *


class HomeView(TemplateView):
    template_name = "home.html"


class ContactView(TemplateView):
    template_name = "contact.html"


class RegistrationView(FormView):
    template_name = 'registration.html'
    form_class = RegistrationForm
    success_url = '/'

    def form_valid(self, form):
        a = form.cleaned_data['username']
        b = form.cleaned_data['email']
        c = form.cleaned_data['password']
        User.objects.create_user(a, b, c)
        return super().form_valid(form)


class LoginView(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = '/'

    def form_valid(self, form):
        a = form.cleaned_data['username']
        b = form.cleaned_data['password']
        user = authenticate(username=a, password=b)

        if user is not None:
            login(self.request, user)
        else:
            return render(self.request, 'login.html', {
                'error': 'Invalid username or password',
                'form': form})

        return super().form_valid(form)


class LogoutView(FormView):
    def get(self, request):
        logout(request)
        return redirect('/')


class ProtectedView(LoginRequiredMixin, TemplateView):
    template_name = 'protected.html'
    login_url = '/login/'


class RestrictedView(TemplateView):
    template_name = 'restricted.html'

    def dispatch(self, request, *args, **kwargs):
        usr = request.user
        if usr.is_authenticated:
            pass
        else:
            return redirect('/login/')
        return super().dispatch(request, *args, **kwargs)


class ArticleListView(ListView):
    template_name = 'articlelist.html'
    queryset = Article.objects.all().order_by("-id")
    context_object_name = 'allarticle'


class ArticleDetailView(DetailView):
    template_name = 'articledetail.html'
    model = Article
    context_object_name = 'articleobject'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # article_object=self.object
        article_id = self.kwargs['pk']
        article_object = Article.objects.get(id=article_id)
        article_object.view_count += 1
        article_object.save()

        return context


class ArticleCreateView(CreateView):
    template_name = 'addnewarticle.html'
    form_class = ArticleForm
    success_url = '/article/list/'

    def dispatch(self, request, *args, **kwargs):
        usr = request.user
        if usr.is_authenticated:
            pass
        else:
            return redirect('/login/')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        logged_in_user = self.request.user
        form.instance.author = logged_in_user
        return super().form_valid(form)


class SearchView(TemplateView):
    template_name = "search.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET['keyword']
        results = Article.objects.filter(
            Q(title__icontains=query) | Q(content__icontains=query) | Q(author__username__icontains=query))
        context['search_results'] = results

        return context

templates/addnewarticle.html
{% extends 'base.html' %}


{% block body %}
<h3>Article Form</h3>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button> Save </button>
	


</form>
{% endblock %}

templates/articledetail.html
{% extends 'base.html' %}


{% block body %}
<h3>{{articleobject.title}}(Viewed {{articleobject.view_count}} times)</h3>
<p>{{articleobject.content}}</p>
<img src="{{articleobject.image.url}}" width="500">
<p>Author:{{articleobject.author}}</p>
<p>Date:{{articleobject.date}}</p>
<h4> comment on this post </h4>

{% for comment in articleobject.comment_set.all|dictsortreversed:'id' %}
<li> {{comment.commentor}} says {{comment.comment}} {{comment.date|timesince}} ago </li>
{% endfor %}

<!-- <div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-width="" data-numposts="5"></div>
 -->
{% endblock %}

templates/articlelist.html
{% extends 'base.html' %}


{% block body %}
<h3>All Articles</h3>

	<table class='table table-bordered table-striped'>
		<thead>
			<tr>
				<th>SN</th>
				<th>Title</th>
				<th>Date</th>
				<th>Author</th>
				<th>Image</th>
				<th>Content</th>
			</tr>
		</thead>
		<tbody>
			{% for article in allarticle %}
			<tr>
				<td>{{forloop.counter}}</td>
				<td><a href="/article/{{article.id}}/detail/">{{article.title}}</a></td>
				<td>{{article.date}}</td>
				<td>{{article.author}}</td>
				<td><img src="{{article.image.url}}" width="100"></td>
				<td>{{article.content|truncatewords:'10'}}</td>



			</tr>
			{% endfor %}
		</tbody>
	</table>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
	<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.3"></script>
	<a href="/">Home</a>
	<a href="/contact/">Contact</a>
	<a href="/article/list/">All Articles</a>
	<a href="/article/create/">Add New Article</a>
	<a href="/protected/">Protected</a>
	<a href="/restricted/">Restricted</a>


	{% if request.user.is_authenticated %}
	     logged in as:<span style='color:blue'>{{ request.user}} </span>
		<a href="/logout/">Logout</a>
     {% else %} 
		<a href="/register/">Registration Form</a>
		<a href="/login/">Login</a>
     {% endif %}

 	<form method="GET" action="{% url 'uasapp:search' %}">
 		<input type="text" name="keyword" placeholder="Search here..." value="{{request.GET.keyword}}">
 		<button> Search </button>
 	</form>

	{% block body %}

	{% endblock %}

	<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5d34415f6d80831228394113/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block body %}
<h3>Contact me at 9898989898</h3>

{% endblock %}

templates/home.html
{% extends 'base.html' %}


{% block body %}
<h3>welcome to home page</h3>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block body %}
<p style="color: red;">{{error}}</p>
<h3> Login Form </h3>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button> login </button>
	


</form>

{% endblock %}

templates/protected.html
{% extends 'base.html' %}
{% block body %}
<h3> you can not enter here without login </h3>

{% endblock %}

templates/registration.html
{% extends 'base.html' %}

{% block body %}

<h3> Registration Form </h3>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button> submit </button>

</form>

{% endblock %}

templates/restricted.html
{% extends 'base.html' %}
{% block body %}
<h3> login nagari chirna na pai hai </h3>

{% endblock %}

templates/search.html
{% extends 'base.html' %}


{% block body %}
<h5>Search Results for <span class="text-info">{{request.GET.keyword}}</span></h5>
{% for article in search_results %}
<li><a href="{% url 'uasapp:articledetail' article.pk %}">{{article.title}}</a></li>
<img src="{{article.image.url}}" width="200">
 
{% endfor %}

{% endblock %}